/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ConectorBD;
import Modelo.Album;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Conti
 */
public class Albumes extends javax.swing.JDialog {
    
    
     private static DefaultTableModel modeloTabla = null;
     DefaultTableCellRenderer Alinear = new DefaultTableCellRenderer();
     private ConectorBD hi;

    /**
     * Creates new form Albumes
     */
    public Albumes(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
         hi=new ConectorBD();
         iniciarTabla();
         cargaralbumes();
         alinear();
         
    }
    
     public void alinear() {
         
         Alinear.setHorizontalAlignment(SwingConstants.CENTER);
          jTAlbum.getColumnModel().getColumn(0).setCellRenderer(Alinear); 
          jTAlbum.getColumnModel().getColumn(1).setCellRenderer(Alinear); 
          jTAlbum.getColumnModel().getColumn(2).setCellRenderer(Alinear); 
           jTAlbum.getColumnModel().getColumn(3).setCellRenderer(Alinear); 
     }
    
     public void borrarFilas() {
        int filas = modeloTabla.getRowCount();
        for (int i = 0; i < filas; i++) {
            modeloTabla.removeRow(0);
        }
        jTAlbum.setModel(modeloTabla);
    }
      public void cargaralbumes()
            
    {
        
       String consulta = "FROM Album";
       List<Album> albumes = hi.lanzarConsulta(consulta);
        System.out.println("resultado" + albumes);
       borrarFilas();
       if (!albumes.isEmpty()) {
            for (Album a : albumes) {
             
                
                //Recuperamos los campos que queremos que se muestren en la tabla.
                String titulo= a.getTitulo();
                
            
                
                Integer precio=a.getPrecio();
                
                String categoria=a.getCategoria();
                
                String nombre=a.getNumcan().getNombre();
                
                 modeloTabla.addRow(new Object[]{
                    titulo,precio,categoria,nombre
                });
                 
                jTAlbum.setModel(modeloTabla);
         
                
                
                jLAlbumes.setText(jTAlbum.getRowCount() + " Albumes encontrados");
            }
          
        } else {
      
             JOptionPane.showMessageDialog(null, "No existen datos");
        }
       
      
        
    }
    
    public void iniciarTabla() {
        //Reajustamos el modelo la tabla para que definir que tipo de dato da cada columna
        //Con esto conseguimos que funcione correctamente la reordenación de filas por columna
        modeloTabla = new DefaultTableModel() {
            Class[] tiposDeColumna = new Class[]{
                java.lang.String.class,java.lang.String.class,java.lang.Integer.class,java.lang.String.class
               
                         };

            @Override
            public Class getColumnClass(int indiceColumna) {
                return tiposDeColumna[indiceColumna];
            }
        };
        //Damos la posibilidad a la tabla de reordenarse en funcion de la columna
        //cuando el usuario pulsa sobre la cabecera
       jTAlbum.setAutoCreateRowSorter(true);

        //Cabeceras de las columnas, mostraremos solamente el titulo, duracion, calificacion y extras.
        modeloTabla.addColumn("Titulo");
         modeloTabla.addColumn("Precio");
        modeloTabla.addColumn("Categoria");
        modeloTabla.addColumn("Nombre-cantante");
            
        jTAlbum.setModel(modeloTabla);
   
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTAlbum = new javax.swing.JTable();
        jLAlbumes = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Listado de Albumes");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 0, 51));
        jButton1.setText("CERRAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTAlbum.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTAlbum);

        jLAlbumes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLAlbumes)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLAlbumes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Albumes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Albumes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Albumes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Albumes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Albumes dialog = new Albumes(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLAlbumes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTAlbum;
    // End of variables declaration//GEN-END:variables
}
